"""
Smoke test — NOT a pytest suite (P4 scope), just 4 runnable assertions.

Covers the risky NEW codepaths the refactor introduced:
  1. Backwards-compat shim imports cleanly (catches sys.path bugs).
  2. Loader stubs (NotImplementedError branches) actually raise.
  3. check_loader rejects DataFrames with wrong schema.
  4. Provenance header on interim CSVs round-trips through pandas.

Run from repo root:
    python tests/smoke_test.py

Exits 0 on success, nonzero with a clear message on any failure.
Assumes `python -m ews.pipeline` (or the shim) has been run at least once so
that data/interim/*.csv exists for assertion #4.
"""

from __future__ import annotations

import os
import subprocess
import sys

import pandas as pd

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(REPO_ROOT, "src"))

from ews.loaders import (  # noqa: E402 — sys.path adjustment above
    check_loader,
    load_fundamentals,
    load_macros,
)

FAILURES: list[str] = []


def check(name: str, condition: bool, detail: str = "") -> None:
    status = "PASS" if condition else "FAIL"
    print(f"  [{status}] {name}" + (f" — {detail}" if detail else ""))
    if not condition:
        FAILURES.append(f"{name}: {detail}")


# -----------------------------------------------------------------------------
# Assertion 1: entry-point wrapper imports cleanly (via subprocess)
# -----------------------------------------------------------------------------
print("\n[1] src/run.py entry point imports cleanly")
result = subprocess.run(
    [sys.executable, "-c",
     f"import sys; sys.path.insert(0, {os.path.join(REPO_ROOT, 'src')!r}); "
     f"import run; "
     f"assert callable(run.main), 'main not callable'; "
     f"print('entry-point OK')"],
    capture_output=True, text=True, cwd=REPO_ROOT,
)
check(
    "src/run.py imports from repo root",
    result.returncode == 0,
    (result.stdout + result.stderr).strip(),
)

# -----------------------------------------------------------------------------
# Assertion 2: loader status — SEC fundamentals live, FRED macros still stubbed
# -----------------------------------------------------------------------------
print("\n[2] Loader status: SEC fundamentals live, FRED macros still stubbed")
dates = pd.DatetimeIndex(pd.date_range("2020-01-31", "2020-12-31", freq="ME"))

df_sec = load_fundamentals(["XOM"], dates, source="sec")
check("load_fundamentals(source='sec') returns a DataFrame", isinstance(df_sec, pd.DataFrame))
try:
    check_loader("fundamentals", df_sec)
    check("SEC fundamentals schema-compliant", True)
except AssertionError as e:
    check("SEC fundamentals schema-compliant", False, str(e)[:120])
check(
    "SEC fundamentals has rows for XOM",
    len(df_sec) >= 1,
    f"rows={len(df_sec)}",
)

try:
    load_macros(dates, source="fred")
    check("load_macros(source='fred') raises", False, "did not raise")
except NotImplementedError as e:
    check(
        "load_macros(source='fred') raises NotImplementedError",
        "FRED" in str(e) or "fred" in str(e),
        f"message mentions FRED: {str(e)[:80]}",
    )

# -----------------------------------------------------------------------------
# Assertion 3: check_loader rejects wrong-schema DataFrames
# -----------------------------------------------------------------------------
print("\n[3] check_loader rejects wrong-schema DataFrames")
try:
    check_loader("fundamentals", pd.DataFrame({"ticker": ["A"]}))
    check("check_loader rejects missing columns", False, "did not raise")
except AssertionError as e:
    check(
        "check_loader rejects missing columns",
        "missing" in str(e).lower(),
        f"message says missing: {str(e)[:80]}",
    )

try:
    check_loader("unknown_loader_xyz", pd.DataFrame())
    check("check_loader rejects unknown name", False, "did not raise")
except AssertionError as e:
    check("check_loader rejects unknown loader name", "unknown" in str(e).lower())

# -----------------------------------------------------------------------------
# Assertion 4: provenance header round-trips through pandas
# -----------------------------------------------------------------------------
print("\n[4] Interim CSV provenance header is parseable")
interim_dir = os.path.join(REPO_ROOT, "data", "interim")
if not os.path.isdir(interim_dir) or not os.listdir(interim_dir):
    check(
        "interim CSVs exist (run pipeline first)",
        False,
        f"no files in {interim_dir} — run `python -m ews.pipeline` first",
    )
else:
    for fname in sorted(os.listdir(interim_dir)):
        if not fname.endswith(".csv"):
            continue
        path = os.path.join(interim_dir, fname)
        with open(path) as f:
            first_line = f.readline().strip()
        check(
            f"{fname} starts with '# generated by ews.pipeline'",
            first_line.startswith("# generated by ews.pipeline"),
            f"first line: {first_line[:60]}",
        )
        try:
            df = pd.read_csv(path, comment="#")
            check(f"{fname} parseable with comment='#'", len(df) > 0)
        except Exception as e:
            check(f"{fname} parseable with comment='#'", False, str(e))


# -----------------------------------------------------------------------------
# Report
# -----------------------------------------------------------------------------
print("\n" + "=" * 60)
if FAILURES:
    print(f"SMOKE TEST FAILED — {len(FAILURES)} assertion(s) failed:")
    for f in FAILURES:
        print(f"  - {f}")
    sys.exit(1)
else:
    print("SMOKE TEST PASSED")
    sys.exit(0)
