"""
Phase 1 pipeline orchestrator.

Three-tier failure policy:
  1. LOADER failure (wrong shape, API error, stub not yet implemented)
     -> RAISE. Fatal. Pipeline stops. Silent fallback from a real data
        source to a placeholder is how capstone demos die.
  2. MODEL-FIT failure (linalg, convergence, perfect separation)
     -> Print a loud WARNING and fall back to the pooled-logit predictions.
        Small-sample model failures are expected on Phase 1 toy data.
  3. CHART / DIAGNOSTIC failure (matplotlib backend, decile bucketing, etc.)
     -> Print a loud WARNING and continue. A missing chart must not
        prevent the other charts from rendering.

Loader outputs are also persisted to data/interim/*.csv after each call,
with a one-line provenance header (`# generated by ews.pipeline on <iso>, ...`).
This is how teammates inspect loader output as files during Phase 2.

The processed panel (`data/processed/panel_phase1.csv`) is written WITHOUT
a provenance header — the baseline SHA256 acceptance test requires that
file to stay byte-identical.
"""

from __future__ import annotations

import datetime as _dt
import os

import pandas as pd

from .config import LABEL_COL, PATHS, TICKERS
from .eval import ablation_analysis, compute_lead_time, evaluate_model, robustness_rolling_window
from .features import build_market_features
from .loaders import load_fundamentals, load_labels, load_macros, load_prices
from .models import model_fe_logit, model_hazard_logit, model_pooled_logit
from .panel import assemble_panel, time_split
from .viz import plot_calibration, plot_firm_risk_trajectory, plot_risk_deciles, plot_roc_pr


# =============================================================================
# Helpers
# =============================================================================

def _write_interim(df: pd.DataFrame, name: str, loader_source: str) -> None:
    """Write an interim DataFrame to PATHS.INTERIM/<name>.csv with a
    one-line provenance header."""
    os.makedirs(PATHS.INTERIM, exist_ok=True)
    path = os.path.join(PATHS.INTERIM, f"{name}.csv")
    now = _dt.datetime.now().isoformat(timespec="seconds")
    with open(path, "w") as f:
        f.write(f"# generated by ews.pipeline on {now}, loader={loader_source}\n")
        df.to_csv(f, index=False)


def _warn(msg: str) -> None:
    print(f"\n  WARNING: {msg}")


# =============================================================================
# Pipeline
# =============================================================================

def main() -> None:
    print("=" * 70)
    print("CREDIT RISK EWS -- PHASE 1 PROTOTYPE")
    print("=" * 70)

    # -- Loaders (tier-1: failures fatal) ------------------------------------
    prices = load_prices(TICKERS)
    _write_interim(prices, "prices", "yfinance")

    market = build_market_features(prices)
    _write_interim(market, "market_features", "derived")

    monthly_dates = (
        prices.pivot(index="date", columns="ticker", values="adj_close")
        .resample("ME").last().index
    )
    # fundamentals = load_fundamentals(TICKERS, monthly_dates, source="placeholder")
    fundamentals = load_fundamentals(TICKERS, monthly_dates, source="sec")
    _write_interim(fundamentals, "fundamentals", "placeholder")

    macros = load_macros(monthly_dates, source="synthetic")
    _write_interim(macros, "macros", "synthetic")

    labels = load_labels(prices, source="drawdown")
    _write_interim(labels, "labels", "drawdown")

    # -- Panel + split ------------------------------------------------------
    panel = assemble_panel(market, fundamentals, macros, labels)
    os.makedirs(PATHS.PROCESSED, exist_ok=True)
    panel.to_csv(os.path.join(PATHS.PROCESSED, "panel_phase2.csv"), index=False)
    print(f"\n  Panel saved to: data/processed/panel_phase2.csv")

    train, val, test = time_split(panel)

    # -- Models (tier-2: model failures warn + fall back to pooled) ---------
    model1, preds1 = model_pooled_logit(train, val, test)

    try:
        model2, preds2 = model_fe_logit(train, val, test)
    except Exception as e:
        _warn(f"FE Logit failed ({e}); falling back to pooled-logit predictions.")
        model2, preds2 = model1, preds1

    try:
        model3, preds3 = model_hazard_logit(train, val, test)
    except Exception as e:
        _warn(f"Hazard Logit failed ({e}); falling back to pooled-logit predictions.")
        model3, preds3 = model1, preds1

    # -- Evaluation ---------------------------------------------------------
    print("\n" + "=" * 70)
    print("EVALUATION RESULTS")
    print("=" * 70)

    eval_split = "val" if len(val) > 0 and val[LABEL_COL].nunique() >= 2 else "train"
    eval_data = val if eval_split == "val" else train

    for name, preds in [("Pooled Logit", preds1), ("FE Logit", preds2), ("Hazard Logit", preds3)]:
        try:
            evaluate_model(eval_data[LABEL_COL], preds[eval_split], name, eval_split.title())
        except Exception as e:
            _warn(f"{name} evaluation failed: {e}")

    print("\nLead Time (Pooled Logit):")
    try:
        compute_lead_time(eval_data, preds1[eval_split])
    except Exception as e:
        _warn(f"Lead-time computation failed: {e}")

    # -- Charts (tier-3: chart failures warn + continue) --------------------
    print("\n" + "=" * 70)
    print("GENERATING CHARTS")
    print("=" * 70)

    y_eval = eval_data[LABEL_COL].reset_index(drop=True)
    preds_by_model = {
        "Pooled Logit": preds1[eval_split],
        "FE Logit":    preds2[eval_split],
        "Hazard Logit": preds3[eval_split],
    }

    for chart_fn, args, name in [
        (plot_roc_pr,       (y_eval, preds_by_model, "phase2_roc_pr.png"),           "ROC/PR"),
        (plot_calibration,  (y_eval, preds1[eval_split], "Pooled Logit",
                             "phase2_calibration.png"),                                "Calibration"),
        (plot_risk_deciles, (y_eval, preds1[eval_split], "Pooled Logit",
                             "phase2_deciles.png"),                                    "Decile"),
        (plot_firm_risk_trajectory,
                            (panel, model1, "Pooled Logit", "phase2_trajectories.png"),
                             "Trajectory"),
    ]:
        try:
            chart_fn(*args)
        except Exception as e:
            _warn(f"{name} chart failed: {e}")

    # -- Diagnostics (tier-3: warn + continue) ------------------------------
    try:
        ablation_analysis(train, eval_data)
    except Exception as e:
        _warn(f"Ablation failed: {e}")

    try:
        robustness_rolling_window(panel)
    except Exception as e:
        _warn(f"Rolling-window robustness failed: {e}")

    # -- Summary ------------------------------------------------------------
    print("\n" + "=" * 70)
    print("PHASE 2 EXPANSION (80 FIRMS) COMPLETE")
    print("=" * 70)
    print("\nArtifacts:")
    print(f"  data/processed/panel_phase2.csv")
    print(f"  data/interim/{{prices,market_features,fundamentals,macros,labels}}.csv")
    print(f"  outputs/figures/phase2_{{roc_pr,calibration,deciles,trajectories}}.png")


if __name__ == "__main__":
    main()
